import type { Article } from '../types'

export const SEED_ARTICLES: Article[] = [
  {
    id: '1',
    title: 'RBI CUTS REPO RATE BY 25 BASIS POINTS IN SURPRISE MOVE',
    slug: 'rbi-cuts-repo-rate',
    subtitle: 'First rate cut in four years signals a decisive shift in monetary policy stance',
    excerpt: 'The Reserve Bank of India reduced its benchmark lending rate to 6.25%, surprising markets and sending the Sensex up 800 points in intraday trade on heavy FII buying.',
    cover_image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=900&q=80',
    reading_time: 4,
    view_count: 12400,
    like_count: 342,
    comment_count: 28,
    author_name: 'Priya Sharma',
    category_name: 'Economy',
    category_color: '#D97706',
    category_slug: 'economy',
    published_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    is_breaking: true,
    is_featured: true,
  },
  {
    id: '2',
    title: 'SENSEX HITS ALL-TIME HIGH AS FII BUYING RETURNS',
    slug: 'sensex-all-time-high',
    subtitle: 'Foreign investors pump ₹4,200 crore into Indian equities in a single session',
    excerpt: 'The BSE Sensex closed at a record 82,450 points driven by heavyweight buying in banking, IT and FMCG sectors as global risk appetite improved.',
    cover_image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=900&q=80',
    reading_time: 3,
    view_count: 8900,
    like_count: 215,
    comment_count: 14,
    author_name: 'Rahul Mehta',
    category_name: 'Markets',
    category_color: '#DC2626',
    category_slug: 'markets',
    published_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    is_breaking: false,
    is_featured: true,
  },
  {
    id: '3',
    title: 'RELIANCE Q3 PROFIT BEATS ESTIMATES BY 12%',
    slug: 'reliance-q3-profit',
    excerpt: 'Reliance Industries reported a consolidated net profit of ₹21,930 crore for Q3 FY26, beating analyst estimates on strong Jio and retail performance.',
    cover_image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=900&q=80',
    reading_time: 5,
    view_count: 6700,
    like_count: 189,
    comment_count: 22,
    author_name: 'Ananya Iyer',
    category_name: 'Business',
    category_color: '#EA580C',
    category_slug: 'business',
    published_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    is_breaking: false,
    is_featured: false,
  },
  {
    id: '4',
    title: 'SEBI TIGHTENS F&O RULES: WHAT RETAIL TRADERS NEED TO KNOW',
    slug: 'sebi-fno-rules',
    excerpt: 'New regulations effective April 2026 raise the minimum contract size and increase margins for weekly options. Here is exactly how it affects you.',
    cover_image: 'https://images.unsplash.com/photo-1642543492481-44e81e3914a7?w=900&q=80',
    reading_time: 6,
    view_count: 15200,
    like_count: 478,
    comment_count: 67,
    author_name: 'Vikram Nair',
    category_name: 'Markets',
    category_color: '#DC2626',
    category_slug: 'markets',
    published_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    is_breaking: false,
    is_featured: true,
  },
  {
    id: '5',
    title: 'BUDGET 2026: INCOME TAX SLABS REVISED UNDER NEW REGIME',
    slug: 'budget-2026-tax-slabs',
    excerpt: 'Finance Minister raised the basic exemption limit to ₹4 lakh and reduced the 20% slab rate to 15% under the new tax regime, benefiting the middle class.',
    cover_image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=900&q=80',
    reading_time: 7,
    view_count: 31000,
    like_count: 892,
    comment_count: 143,
    author_name: 'Deepa Krishnan',
    category_name: 'Personal Finance',
    category_color: '#16A34A',
    category_slug: 'finance',
    published_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    is_breaking: false,
    is_featured: true,
  },
  {
    id: '6',
    title: 'UPI CROSSES 20 BILLION TRANSACTIONS IN FEBRUARY 2026',
    slug: 'upi-20-billion',
    excerpt: "India's Unified Payments Interface hit a new milestone with 20.06 billion transactions worth ₹20.07 lakh crore in February, NPCI data showed.",
    cover_image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=900&q=80',
    reading_time: 3,
    view_count: 9400,
    like_count: 267,
    comment_count: 31,
    author_name: 'Arjun Kapoor',
    category_name: 'Technology',
    category_color: '#4F46E5',
    category_slug: 'tech',
    published_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    is_breaking: false,
    is_featured: false,
  },
]

export const SEED_CATEGORIES = [
  { id: '1', name: 'Markets',         slug: 'markets',  color: '#DC2626', article_count: 24 },
  { id: '2', name: 'Business',        slug: 'business', color: '#EA580C', article_count: 18 },
  { id: '3', name: 'Economy',         slug: 'economy',  color: '#D97706', article_count: 15 },
  { id: '4', name: 'Personal Finance',slug: 'finance',  color: '#16A34A', article_count: 12 },
  { id: '5', name: 'Technology',      slug: 'tech',     color: '#4F46E5', article_count: 20 },
  { id: '6', name: 'Investing',       slug: 'investing',color: '#7C3AED', article_count: 9  },
]